import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Update the function to accept BOTH CSV files
def plot_random_10_comparison(
    baseline_csv="data/dataset_w_baseline.csv", 
    vit_csv="data/dataset_w_changeStar.csv"
):
    print("📊 Loading datasets and merging...")
    
    # Load both datasets
    df_baseline = pd.read_csv(baseline_csv)
    df_vit = pd.read_csv(vit_csv)
    
    # Merge them together using the contractId. 
    # An inner join ensures we only plot projects that successfully completed both pipelines.
    df = pd.merge(df_baseline, df_vit, on='contractId')
    
    # Drop any rows that might have failed to process and contain NaNs
    df = df.dropna(subset=['vit_delta_00_to_25', 'delta_00_to_25'])
    
    print("📊 Extracting 10 random projects...")
    # Randomly sample 10 projects. 
    # (Remove random_state=42 if you want different projects every time you run it)
    sample_df = df.sample(n=10, random_state=42)
    
    # The exact column suffixes generated by your string slicing (t0_name[:2])
    intervals = ['00_to_25', '25_to_50', '50_to_75', '75_to_10', '10_to_po']
    
    # Clean labels for the X-axis of the plots
    x_labels = ['0-25%', '25-50%', '50-75%', '75-100%', 'Post']

    # Setup the matplotlib 2x5 grid
    fig, axes = plt.subplots(nrows=2, ncols=5, figsize=(20, 8), sharey=True)
    axes = axes.flatten() # Flatten the 2D array of axes for easy looping

    for i, (idx, row) in enumerate(sample_df.iterrows()):
        ax = axes[i]
        
        # Extract the 5 chronological values for both models
        baseline_scores = [row[f'delta_{intv}'] for intv in intervals]
        vit_scores = [row[f'vit_delta_{intv}'] for intv in intervals]
        
        # Plot Baseline as a dashed gray line
        ax.plot(x_labels, baseline_scores, marker='o', linestyle='--', 
                color='gray', linewidth=2, label='Baseline (Pixels)')
        
        # Plot ViT as a solid blue line
        ax.plot(x_labels, vit_scores, marker='s', linestyle='-', 
                color='#1f77b4', linewidth=2, label='ViT (Semantic AI)')
        
        # Formatting for each subplot
        ax.set_title(f"Contract: {row['contractId']}", fontsize=11, fontweight='bold')
        ax.set_ylim(-0.05, 1.05)
        ax.grid(True, linestyle=':', alpha=0.6)
        
        # Rotate X labels slightly so they don't overlap
        ax.tick_params(axis='x', rotation=45)
        
        # Only show the legend on the very first plot to keep it clean
        if i == 0:
            ax.legend(loc='upper right', fontsize=10)

    # Polish the overall layout
    fig.suptitle("Construction Curves: Pixel Baseline vs Semantic ViT", 
                 fontsize=20, fontweight='bold', y=1.02)
    fig.supylabel("Mean Change Confidence Score", fontsize=14, x=0.01)
    
    # Adjust spacing so titles and rotated labels fit perfectly
    plt.tight_layout()
    
    # Save the master plot
    out_img = "data/baseline_vs_vit_10projects.png"
    plt.savefig(out_img, dpi=600, bbox_inches='tight')
    print(f"✅ Master plot saved to {out_img}")
    
    # Display it on screen
    plt.show()

if __name__ == "__main__":
    # Make sure these filenames match whatever you actually named your CSVs!
    plot_random_10_comparison(
        baseline_csv="data/dataset_w_baseline.csv", 
        vit_csv="data/dataset_w_changeStar.csv"
    )